package fastcampus.aop.part2.chapter02

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import android.widget.Button
import android.widget.NumberPicker
import android.widget.TextView
import android.widget.Toast
import androidx.core.view.isVisible

class MainActivity : AppCompatActivity() {

    private val clearButton: Button by lazy {
        findViewById<Button>(R.id.clearButton)
    }
    private val addButton: Button by lazy {
        findViewById<Button>(R.id.addButton)
    }

    private val runButton: Button by lazy {
        findViewById<Button>(R.id.runButton)
    }

    private val numberPicker: NumberPicker by lazy{
        findViewById<NumberPicker>(R.id.numberPicker)
    }

    private val AutoGeneratedNumList: List<TextView> by lazy {
        listOf<TextView>(
                    findViewById<TextView>(R.id.first_generated_num),
                    findViewById<TextView>(R.id.second_generated_num),
                    findViewById<TextView>(R.id.third_generated_num),
                    findViewById<TextView>(R.id.fourth_generated_num),
                    findViewById<TextView>(R.id.fifth_generated_num),
                    findViewById<TextView>(R.id.sixth_generated_num)
        )
    }

    private var didRun = false

    private val pickedByUserNumberSet = hashSetOf<Int>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        numberPicker.minValue = 1
        numberPicker.maxValue = 45

        initRunButton()
        initAddButton()
    }
    private fun initRunButton(){
        runButton.setOnClickListener{
            val list = getRandomNumber()

            Log.d("MainActivity", list.toString())
        }
    }

    private fun initAddButton() {
        addButton.setOnClickListener{

            if (didRun) {
                Toast.makeText(this, "초기화 후에 시도해주세요. ", Toast.LENGTH_SHORT).show()
                return@setOnClickListener
            }

            if (pickedByUserNumberSet.size >= 5){
                Toast.makeText(this, "번호는 5개까지만 선택할 수 있습니다. ", Toast.LENGTH_SHORT).show()
                return@setOnClickListener
            }

            if (pickedByUserNumberSet.contains(numberPicker.value)) {
                Toast.makeText(this, "이미 선택한 번호입니다. ", Toast.LENGTH_SHORT).show()
                return@setOnClickListener
            }

            val textView = AutoGeneratedNumList[pickedByUserNumberSet.size]
            Log.d("MainActivity", AutoGeneratedNumList[pickedByUserNumberSet.size].text.toString())
            textView.isVisible = true
            textView.text = numberPicker.value.toString()

            pickedByUserNumberSet.add(numberPicker.value)



        }
    }

    private fun getRandomNumber(): List<Int>{
        val numberList = mutableListOf<Int>()
            .apply {
                for (i in 1..45){
                    this.add(i)
                }
            }
        numberList.shuffle()

        val newList = numberList.subList(0,6)

        return newList.sorted()
    }
}